// <auto-generated />
using EcoIndicators.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EcoIndicators.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251208130011_publicWater")]
    partial class publicWater
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EcoIndicators.Models.MakStat.Public_water_supply", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Abstracted_water")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Ground_water")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Lake")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Reservoir")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Springs")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Water_taken_from_other_water_supply_systems")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Watercourse")
                        .HasColumnType("numeric");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Public_water_supplys");
                });

            modelBuilder.Entity("EcoIndicators.Models.MakStat.SectorCO2", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Agriculture")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Energy")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Heat")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Industrial_processes")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Transport")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Waste")
                        .HasColumnType("numeric");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("SectorCO2s");
                });

            modelBuilder.Entity("EcoIndicators.Models.MakStat.TotalEmissionCO2", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("TotalEmissionCO2s");
                });

            modelBuilder.Entity("EcoIndicators.Models.MakStat.TotalEmissionSO2", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Combustion_processes")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Other")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Production_processes")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Transport")
                        .HasColumnType("numeric");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("TotalEmissionSO2s");
                });

            modelBuilder.Entity("EcoIndicators.Models.MakStat.Water_For_Production", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Fresh_drinking")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Fresh_water_tech")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Recurculation_fresh_water_added")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Reused_water_afterCooling")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Reused_water_afterPurifying")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Total_recirculation_water")
                        .HasColumnType("numeric");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Water_For_Productions");
                });

            modelBuilder.Entity("EcoIndicators.Models.MakStat.Water_supplied_by_business_entities", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Ground_water")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Lakes")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Reservoirs")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Springs")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Water_courses")
                        .HasColumnType("numeric");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Water_supplied_by_business_entitiess");
                });
#pragma warning restore 612, 618
        }
    }
}
